/** Convert JS camelCase member object → Supabase snake_case row */
export function memberToRow(m) {
  return {
    first_name:              m.firstName              ?? '',
    last_name:               m.lastName               ?? '',
    gender:                  m.gender                 ?? null,
    date_of_birth:           m.dateOfBirth            || null,
    grade:                   m.grade                  ?? null,
    age_on_jan1:             m.ageOnJan1              ?? null,
    member_type:             m.memberType             ?? 'player',
    mobile:                  m.mobile                 ?? null,
    home_phone:              m.homePhone              ?? null,
    email:                   m.email                  ?? null,
    street_address:          m.streetAddress          ?? null,
    suburb:                  m.suburb                 ?? null,
    city:                    m.city                   ?? null,
    postcode:                m.postcode               ?? null,
    institution:             m.institution            ?? null,
    medical_notes:           m.medicalNotes           ?? null,
    photo:                   m.photo                  ?? null,
    registration_mode:       m.registrationMode       ?? null,
    family_group_name:       m.familyGroupName        ?? null,
    accepted_terms:          m.acceptedTerms          ?? false,
    linked_child_name:       m.linkedChildName        ?? null,
    parent_first_name:       m.parentFirstName        ?? null,
    parent_last_name:        m.parentLastName         ?? null,
    parent_email:            m.parentEmail            ?? null,
    parent_mobile:           m.parentMobile           ?? null,
    parent_relationship:     m.parentRelationship     ?? null,
    parent_occupation:       m.parentOccupation       ?? null,
    parent_volunteer:        m.parentVolunteer        ?? false,
    parent_volunteer_roles:  m.parentVolunteerRoles   ?? [],
    parent_volunteer_other:  m.parentVolunteerOther   ?? null,
    parent_is_player:        m.parentIsPlayer         ?? false,
    parent2_first_name:      m.parent2FirstName       ?? null,
    parent2_last_name:       m.parent2LastName        ?? null,
    parent2_email:           m.parent2Email           ?? null,
    parent2_mobile:          m.parent2Mobile          ?? null,
    parent2_relationship:    m.parent2Relationship    ?? null,
    parent2_occupation:      m.parent2Occupation      ?? null,
    parent2_volunteer:       m.parent2Volunteer       ?? false,
    parent2_volunteer_roles: m.parent2VolunteerRoles  ?? [],
    parent2_volunteer_other: m.parent2VolunteerOther  ?? null,
    parent2_is_player:       m.parent2IsPlayer        ?? false,
  }
}

/** Convert Supabase snake_case row → JS camelCase member object */
export function rowToMember(r) {
  return {
    id:                    r.id,
    regId:                 r.reg_id,
    firstName:             r.first_name,
    lastName:              r.last_name,
    gender:                r.gender,
    dateOfBirth:           r.date_of_birth,
    grade:                 r.grade,
    ageOnJan1:             r.age_on_jan1,
    memberType:            r.member_type,
    mobile:                r.mobile,
    homePhone:             r.home_phone,
    email:                 r.email,
    streetAddress:         r.street_address,
    suburb:                r.suburb,
    city:                  r.city,
    postcode:              r.postcode,
    institution:           r.institution,
    medicalNotes:          r.medical_notes,
    photo:                 r.photo,
    registrationMode:      r.registration_mode,
    familyGroupName:       r.family_group_name,
    acceptedTerms:         r.accepted_terms,
    linkedChildName:       r.linked_child_name,
    parentFirstName:       r.parent_first_name,
    parentLastName:        r.parent_last_name,
    parentEmail:           r.parent_email,
    parentMobile:          r.parent_mobile,
    parentRelationship:    r.parent_relationship,
    parentOccupation:      r.parent_occupation,
    parentVolunteer:       r.parent_volunteer,
    parentVolunteerRoles:  r.parent_volunteer_roles  ?? [],
    parentVolunteerOther:  r.parent_volunteer_other,
    parentIsPlayer:        r.parent_is_player,
    parent2FirstName:      r.parent2_first_name,
    parent2LastName:       r.parent2_last_name,
    parent2Email:          r.parent2_email,
    parent2Mobile:         r.parent2_mobile,
    parent2Relationship:   r.parent2_relationship,
    parent2Occupation:     r.parent2_occupation,
    parent2Volunteer:      r.parent2_volunteer,
    parent2VolunteerRoles: r.parent2_volunteer_roles ?? [],
    parent2VolunteerOther: r.parent2_volunteer_other,
    parent2IsPlayer:       r.parent2_is_player,
    createdAt:             r.created_at,
  }
}
