export const NZ_SUBURBS = [
  // Auckland Central
  { suburb: 'Auckland CBD', city: 'Auckland', postcode: '1010' },
  { suburb: 'Parnell', city: 'Auckland', postcode: '1052' },
  { suburb: 'Newmarket', city: 'Auckland', postcode: '1023' },
  { suburb: 'Grafton', city: 'Auckland', postcode: '1023' },
  { suburb: 'Epsom', city: 'Auckland', postcode: '1023' },
  { suburb: 'Remuera', city: 'Auckland', postcode: '1050' },
  { suburb: 'Ellerslie', city: 'Auckland', postcode: '1051' },
  { suburb: 'Penrose', city: 'Auckland', postcode: '1061' },
  { suburb: 'Onehunga', city: 'Auckland', postcode: '1061' },
  { suburb: 'Mount Wellington', city: 'Auckland', postcode: '1060' },
  { suburb: 'Panmure', city: 'Auckland', postcode: '1072' },
  { suburb: 'Glen Innes', city: 'Auckland', postcode: '1072' },
  { suburb: 'Meadowbank', city: 'Auckland', postcode: '1072' },
  { suburb: 'Mission Bay', city: 'Auckland', postcode: '1071' },
  { suburb: 'Kohimarama', city: 'Auckland', postcode: '1071' },
  { suburb: 'St Heliers', city: 'Auckland', postcode: '1071' },
  { suburb: 'Orakei', city: 'Auckland', postcode: '1071' },
  { suburb: 'Mount Eden', city: 'Auckland', postcode: '1024' },
  { suburb: 'Sandringham', city: 'Auckland', postcode: '1025' },
  { suburb: 'Kingsland', city: 'Auckland', postcode: '1021' },
  { suburb: 'Grey Lynn', city: 'Auckland', postcode: '1021' },
  { suburb: 'Ponsonby', city: 'Auckland', postcode: '1011' },
  { suburb: 'Freemans Bay', city: 'Auckland', postcode: '1011' },
  { suburb: 'Herne Bay', city: 'Auckland', postcode: '1011' },
  { suburb: 'St Marys Bay', city: 'Auckland', postcode: '1011' },
  { suburb: 'Westmere', city: 'Auckland', postcode: '1022' },
  { suburb: 'Point Chevalier', city: 'Auckland', postcode: '1022' },
  { suburb: 'Royal Oak', city: 'Auckland', postcode: '1023' },
  { suburb: 'Three Kings', city: 'Auckland', postcode: '1042' },
  { suburb: 'Mount Roskill', city: 'Auckland', postcode: '1041' },
  { suburb: 'Lynfield', city: 'Auckland', postcode: '1042' },
  { suburb: 'Hillsborough', city: 'Auckland', postcode: '1042' },
  { suburb: 'Otahuhu', city: 'Auckland', postcode: '1062' },
  // West Auckland
  { suburb: 'Avondale', city: 'Auckland', postcode: '1026' },
  { suburb: 'New Lynn', city: 'Auckland', postcode: '0600' },
  { suburb: 'Blockhouse Bay', city: 'Auckland', postcode: '0600' },
  { suburb: 'Glen Eden', city: 'Auckland', postcode: '0602' },
  { suburb: 'Titirangi', city: 'Auckland', postcode: '0604' },
  { suburb: 'Henderson', city: 'Auckland', postcode: '0612' },
  { suburb: 'Ranui', city: 'Auckland', postcode: '0612' },
  { suburb: 'Massey', city: 'Auckland', postcode: '0614' },
  { suburb: 'Swanson', city: 'Auckland', postcode: '0614' },
  { suburb: 'Te Atatu Peninsula', city: 'Auckland', postcode: '0610' },
  { suburb: 'West Harbour', city: 'Auckland', postcode: '0618' },
  { suburb: 'Hobsonville', city: 'Auckland', postcode: '0618' },
  { suburb: 'Kumeu', city: 'Auckland', postcode: '0810' },
  { suburb: 'Huapai', city: 'Auckland', postcode: '0810' },
  { suburb: 'Helensville', city: 'Auckland', postcode: '0800' },
  // South Auckland
  { suburb: 'Mangere', city: 'Auckland', postcode: '2022' },
  { suburb: 'Mangere Bridge', city: 'Auckland', postcode: '2022' },
  { suburb: 'Papatoetoe', city: 'Auckland', postcode: '2025' },
  { suburb: 'Manurewa', city: 'Auckland', postcode: '2102' },
  { suburb: 'Clendon', city: 'Auckland', postcode: '2103' },
  { suburb: 'Papakura', city: 'Auckland', postcode: '2110' },
  { suburb: 'Takanini', city: 'Auckland', postcode: '2112' },
  { suburb: 'Pukekohe', city: 'Auckland', postcode: '2120' },
  { suburb: 'Clarks Beach', city: 'Auckland', postcode: '2123' },
  // East Auckland
  { suburb: 'Pakuranga', city: 'Auckland', postcode: '2010' },
  { suburb: 'Highland Park', city: 'Auckland', postcode: '2010' },
  { suburb: 'Sunnyhills', city: 'Auckland', postcode: '2010' },
  { suburb: 'Bucklands Beach', city: 'Auckland', postcode: '2012' },
  { suburb: 'Farm Cove', city: 'Auckland', postcode: '2012' },
  { suburb: 'Half Moon Bay', city: 'Auckland', postcode: '2012' },
  { suburb: 'Botany Downs', city: 'Auckland', postcode: '2013' },
  { suburb: 'Northpark', city: 'Auckland', postcode: '2013' },
  { suburb: 'Howick', city: 'Auckland', postcode: '2014' },
  { suburb: 'Cockle Bay', city: 'Auckland', postcode: '2014' },
  { suburb: 'Flat Bush', city: 'Auckland', postcode: '2019' },
  { suburb: 'Dannemora', city: 'Auckland', postcode: '2016' },
  { suburb: 'Beachlands', city: 'Auckland', postcode: '2018' },
  { suburb: 'Maraetai', city: 'Auckland', postcode: '2018' },
  { suburb: 'Clevedon', city: 'Auckland', postcode: '2248' },
  // North Shore
  { suburb: 'Takapuna', city: 'Auckland', postcode: '0622' },
  { suburb: 'Belmont', city: 'Auckland', postcode: '0622' },
  { suburb: 'Bayswater', city: 'Auckland', postcode: '0622' },
  { suburb: 'Devonport', city: 'Auckland', postcode: '0624' },
  { suburb: 'Cheltenham', city: 'Auckland', postcode: '0624' },
  { suburb: 'Birkenhead', city: 'Auckland', postcode: '0626' },
  { suburb: 'Beach Haven', city: 'Auckland', postcode: '0626' },
  { suburb: 'Birkdale', city: 'Auckland', postcode: '0626' },
  { suburb: 'Northcote', city: 'Auckland', postcode: '0627' },
  { suburb: 'Hillcrest', city: 'Auckland', postcode: '0627' },
  { suburb: 'Glenfield', city: 'Auckland', postcode: '0629' },
  { suburb: 'Sunnynook', city: 'Auckland', postcode: '0620' },
  { suburb: 'Forrest Hill', city: 'Auckland', postcode: '0620' },
  { suburb: 'Milford', city: 'Auckland', postcode: '0620' },
  { suburb: 'Totara Vale', city: 'Auckland', postcode: '0629' },
  { suburb: 'Bayview', city: 'Auckland', postcode: '0629' },
  { suburb: 'Browns Bay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Torbay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Long Bay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Mairangi Bay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Campbells Bay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Murrays Bay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Rothesay Bay', city: 'Auckland', postcode: '0630' },
  { suburb: 'Albany', city: 'Auckland', postcode: '0632' },
  { suburb: 'Oteha', city: 'Auckland', postcode: '0632' },
  { suburb: 'Northcross', city: 'Auckland', postcode: '0630' },
  // Rodney / Hibiscus Coast
  { suburb: 'Silverdale', city: 'Auckland', postcode: '0932' },
  { suburb: 'Whangaparaoa', city: 'Auckland', postcode: '0932' },
  { suburb: 'Millwater', city: 'Auckland', postcode: '0932' },
  { suburb: 'Orewa', city: 'Auckland', postcode: '0931' },
  { suburb: 'Stanmore Bay', city: 'Auckland', postcode: '0932' },
  { suburb: 'Manly', city: 'Auckland', postcode: '0930' },
  { suburb: 'Warkworth', city: 'Auckland', postcode: '0910' },
  // Wellington
  { suburb: 'Wellington CBD', city: 'Wellington', postcode: '6011' },
  { suburb: 'Thorndon', city: 'Wellington', postcode: '6011' },
  { suburb: 'Te Aro', city: 'Wellington', postcode: '6011' },
  { suburb: 'Kelburn', city: 'Wellington', postcode: '6012' },
  { suburb: 'Wadestown', city: 'Wellington', postcode: '6012' },
  { suburb: 'Karori', city: 'Wellington', postcode: '6012' },
  { suburb: 'Aro Valley', city: 'Wellington', postcode: '6021' },
  { suburb: 'Mount Cook', city: 'Wellington', postcode: '6021' },
  { suburb: 'Newtown', city: 'Wellington', postcode: '6021' },
  { suburb: 'Brooklyn', city: 'Wellington', postcode: '6021' },
  { suburb: 'Island Bay', city: 'Wellington', postcode: '6023' },
  { suburb: 'Berhampore', city: 'Wellington', postcode: '6023' },
  { suburb: 'Mornington', city: 'Wellington', postcode: '6022' },
  { suburb: 'Vogeltown', city: 'Wellington', postcode: '6022' },
  { suburb: 'Ngaio', city: 'Wellington', postcode: '6035' },
  { suburb: 'Khandallah', city: 'Wellington', postcode: '6035' },
  { suburb: 'Johnsonville', city: 'Wellington', postcode: '6037' },
  { suburb: 'Newlands', city: 'Wellington', postcode: '6037' },
  { suburb: 'Churton Park', city: 'Wellington', postcode: '6037' },
  { suburb: 'Paparangi', city: 'Wellington', postcode: '6037' },
  { suburb: 'Tawa', city: 'Wellington', postcode: '5028' },
  { suburb: 'Porirua', city: 'Porirua', postcode: '5022' },
  { suburb: 'Titahi Bay', city: 'Porirua', postcode: '5022' },
  { suburb: 'Whitby', city: 'Porirua', postcode: '5024' },
  { suburb: 'Lower Hutt', city: 'Lower Hutt', postcode: '5010' },
  { suburb: 'Petone', city: 'Lower Hutt', postcode: '5012' },
  { suburb: 'Eastbourne', city: 'Lower Hutt', postcode: '5013' },
  { suburb: 'Wainuiomata', city: 'Lower Hutt', postcode: '5014' },
  { suburb: 'Upper Hutt', city: 'Upper Hutt', postcode: '5018' },
  { suburb: 'Stokes Valley', city: 'Upper Hutt', postcode: '5019' },
  { suburb: 'Paraparaumu', city: 'Kapiti Coast', postcode: '5032' },
  { suburb: 'Waikanae', city: 'Kapiti Coast', postcode: '5036' },
  // Christchurch
  { suburb: 'Christchurch CBD', city: 'Christchurch', postcode: '8011' },
  { suburb: 'Merivale', city: 'Christchurch', postcode: '8014' },
  { suburb: 'St Albans', city: 'Christchurch', postcode: '8014' },
  { suburb: 'Addington', city: 'Christchurch', postcode: '8024' },
  { suburb: 'Spreydon', city: 'Christchurch', postcode: '8024' },
  { suburb: 'Somerfield', city: 'Christchurch', postcode: '8024' },
  { suburb: 'Sydenham', city: 'Christchurch', postcode: '8023' },
  { suburb: 'Woolston', city: 'Christchurch', postcode: '8023' },
  { suburb: 'Opawa', city: 'Christchurch', postcode: '8023' },
  { suburb: 'Cashmere', city: 'Christchurch', postcode: '8022' },
  { suburb: 'Riccarton', city: 'Christchurch', postcode: '8041' },
  { suburb: 'Ilam', city: 'Christchurch', postcode: '8041' },
  { suburb: 'Avonhead', city: 'Christchurch', postcode: '8042' },
  { suburb: 'Sockburn', city: 'Christchurch', postcode: '8042' },
  { suburb: 'Hornby', city: 'Christchurch', postcode: '8042' },
  { suburb: 'Wigram', city: 'Christchurch', postcode: '8042' },
  { suburb: 'Halswell', city: 'Christchurch', postcode: '8025' },
  { suburb: 'Fendalton', city: 'Christchurch', postcode: '8052' },
  { suburb: 'Burnside', city: 'Christchurch', postcode: '8053' },
  { suburb: 'Bishopdale', city: 'Christchurch', postcode: '8053' },
  { suburb: 'Papanui', city: 'Christchurch', postcode: '8053' },
  { suburb: 'Redwood', city: 'Christchurch', postcode: '8051' },
  { suburb: 'Northwood', city: 'Christchurch', postcode: '8051' },
  { suburb: 'Belfast', city: 'Christchurch', postcode: '8051' },
  { suburb: 'Harewood', city: 'Christchurch', postcode: '8051' },
  { suburb: 'New Brighton', city: 'Christchurch', postcode: '8061' },
  { suburb: 'Linwood', city: 'Christchurch', postcode: '8062' },
  { suburb: 'Bromley', city: 'Christchurch', postcode: '8062' },
  // Hamilton
  { suburb: 'Hamilton CBD', city: 'Hamilton', postcode: '3204' },
  { suburb: 'Hamilton East', city: 'Hamilton', postcode: '3216' },
  { suburb: 'Hillcrest Hamilton', city: 'Hamilton', postcode: '3216' },
  { suburb: 'Claudelands', city: 'Hamilton', postcode: '3214' },
  { suburb: 'Frankton', city: 'Hamilton', postcode: '3204' },
  { suburb: 'Nawton', city: 'Hamilton', postcode: '3200' },
  { suburb: 'Dinsdale', city: 'Hamilton', postcode: '3202' },
  { suburb: 'Chartwell', city: 'Hamilton', postcode: '3210' },
  { suburb: 'Rototuna', city: 'Hamilton', postcode: '3210' },
  { suburb: 'Flagstaff', city: 'Hamilton', postcode: '3210' },
  { suburb: 'Te Rapa', city: 'Hamilton', postcode: '3200' },
  { suburb: 'Queenwood', city: 'Hamilton', postcode: '3210' },
  // Tauranga
  { suburb: 'Tauranga CBD', city: 'Tauranga', postcode: '3110' },
  { suburb: 'Otumoetai', city: 'Tauranga', postcode: '3110' },
  { suburb: 'Matua', city: 'Tauranga', postcode: '3110' },
  { suburb: 'Bethlehem', city: 'Tauranga', postcode: '3110' },
  { suburb: 'Bellevue', city: 'Tauranga', postcode: '3110' },
  { suburb: 'Greerton', city: 'Tauranga', postcode: '3112' },
  { suburb: 'Gate Pa', city: 'Tauranga', postcode: '3112' },
  { suburb: 'Welcome Bay', city: 'Tauranga', postcode: '3112' },
  { suburb: 'Mount Maunganui', city: 'Tauranga', postcode: '3116' },
  { suburb: 'Papamoa', city: 'Tauranga', postcode: '3118' },
  // Dunedin
  { suburb: 'Dunedin CBD', city: 'Dunedin', postcode: '9016' },
  { suburb: 'North Dunedin', city: 'Dunedin', postcode: '9016' },
  { suburb: 'South Dunedin', city: 'Dunedin', postcode: '9012' },
  { suburb: 'St Kilda', city: 'Dunedin', postcode: '9012' },
  { suburb: 'St Clair', city: 'Dunedin', postcode: '9012' },
  { suburb: 'Caversham', city: 'Dunedin', postcode: '9012' },
  { suburb: 'Musselburgh', city: 'Dunedin', postcode: '9013' },
  { suburb: 'Mosgiel', city: 'Dunedin', postcode: '9024' },
  { suburb: 'Green Island', city: 'Dunedin', postcode: '9018' },
  // Other cities
  { suburb: 'Palmerston North', city: 'Palmerston North', postcode: '4410' },
  { suburb: 'Napier', city: 'Napier', postcode: '4110' },
  { suburb: 'Hastings', city: 'Hastings', postcode: '4120' },
  { suburb: 'Nelson', city: 'Nelson', postcode: '7010' },
  { suburb: 'Invercargill', city: 'Invercargill', postcode: '9810' },
  { suburb: 'Rotorua', city: 'Rotorua', postcode: '3010' },
  { suburb: 'Whangarei', city: 'Whangarei', postcode: '0110' },
  { suburb: 'New Plymouth', city: 'New Plymouth', postcode: '4310' },
  { suburb: 'Gisborne', city: 'Gisborne', postcode: '4010' },
  { suburb: 'Timaru', city: 'Timaru', postcode: '7910' },
  { suburb: 'Blenheim', city: 'Blenheim', postcode: '7201' },
  { suburb: 'Whanganui', city: 'Whanganui', postcode: '4500' },
  { suburb: 'Levin', city: 'Levin', postcode: '5510' },
  { suburb: 'Masterton', city: 'Masterton', postcode: '5810' },
  { suburb: 'Feilding', city: 'Feilding', postcode: '4702' },
]

export function searchSuburbs(query) {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase()
  return NZ_SUBURBS.filter(({ suburb, city }) =>
    suburb.toLowerCase().includes(q) || city.toLowerCase().includes(q)
  ).slice(0, 8)
}
